### ISSUE TITLE
Anwendungsfalldiagramm erstellen

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#17]
Erstellen Sie ein Anwendungsfalldiagramm für das Praktikumsprojekt und beschreiben Sie alle Anwendungsfälle gemäß der in der Vorlesung besprochenen Anwendungsfallbeschreibung (siehe Oestereich, Analyse und Design mit UML 2.1/3/5, S. 119 (8. Auflage), S. 126 (10. Auflage), S. 75 (11.Auflage)). Anwendungsfalldiagramm und Anwendungsfallbeschreibungen stellen Sie in das Wiki Ihres Github Repositories

**Comment by juliakt** [comment]
![nooo](https://user-images.githubusercontent.com/43878732/48514268-4bbc4680-e85e-11e8-9287-202bffae0ea0.png)


leute ich hab keine lust mehr

**Comment by juliakt** [comment]
versteht ihr wo der unterschied zwischen user story und anwendungsfall liegt? die Anwendungsfälle sollen wir nämlich auch nochmal detailliert im wiki beschreiben

**Comment by toasthans** [comment]
User Stories are centered on the result and the benefit of the thing you're describing, whereas Use Cases can be more granular, and describe how your system will act.

via My IPhone

**Comment by Blu3berry** [comment]
![anwenungsfall](https://user-images.githubusercontent.com/43879315/48561755-f2512780-e8f0-11e8-8f2c-ce7bfd377475.png)
