### ISSUE TITLE
Fachklassenmodell erstellen

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#19]
Erstellen Sie ein Fachklassenmodell (Analyseklassenmodell) für Ihr Praktikumsprojekt. Das Fachklassenmodell stellen Sie in das Wiki Ihres Github Repositories

**Comment by Blu3berry** [comment]
![fachklasse](https://user-images.githubusercontent.com/43879315/48560426-13644900-e8ee-11e8-8d58-9b7791d57823.png)
so ok?
