### ISSUE TITLE
TODO Anwendungsfälle beschreiben

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#21]

**Comment by toasthans** [comment]
<img width="468" alt="hilfe" src="https://user-images.githubusercontent.com/43779031/48574399-5c78c500-e90f-11e8-91f3-91970f1e8c48.png">

**Comment by toasthans** [comment]
<img width="482" alt="musik" src="https://user-images.githubusercontent.com/43779031/48574993-f8570080-e910-11e8-8126-7dfb9db3f505.png">
