### ISSUE TITLE
TODO User Stories sammeln und aufschreiben (->Product Backlog)

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#22]

**Comment by toasthans** [comment]
ich könnts schon machen wenn ich userstories verstehen würde. irgendjemand ne genaue erklärung dafür? ich weiß nämlich grad noch nicht obs auf die user oder aufs produkt oder beides bezogen ist

**Comment by juliakt** [comment]
Hast du schon das auf moodle dazu gelesen? Also unter Praktikumsprojekt und über dem abgabebereich für Sprint 0
