### ISSUE TITLE
Issues formulieren/Erklärung user Stories

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#24]
- generelle Issues für Product Backlog formulieren (was am Ende erreicht sein soll)

- wir sollen alle Issues als User Stories formulieren ("Ich als Auftraggeber möchte ein Fachklassendiagramm haben, was das System visualisiert bla bla.."), außer solche Aufgaben wie "Seite im Wiki aktualisieren", die sind nur für uns und für den User uninteressant, solche Issues mit TODO markieren 

- TODO nur für uns, die restlichen sind gleichzeitig User Stories

- User Stories haben (oder sollten bald haben) Namen (Name des Issues), Beschreibung ("ich als... möchte...") und Akzeptanzkriterien (Auflistung was erfüllt sein muss damit issue als abgeschlossen gilt) 
 

(ist so ziemlich die Zusammenfassung der heutigen Vorlesung)

Tipps wie man gute Userstories schreibt:
http://www.romanpichler.com/blog/10-tips-writing-good-user-stories/

**Comment by juliakt** [comment]
Product Backlog und User Stories

Der Product Backlog ist die Liste aller bekannten Anforderungen zu einem Produkt/Projekt. Die Anforderungen werden in Form von User Stories angegeben.

Eine User Story besteht aus

-Name

-einem Satz nach dem Muster:

Als <Benutzerrolle> will ich <das Ziel>, um <Nutzen> 

-Akzeptanzkriterien

Benutzerrolle = Benutzergruppe eines Systems (= Akteur)

Ziel = was gemacht werden soll

Nutzen = Ziel der User Story; der Nutzen ist bei einer User Story optional

**Comment by Zzerr0r** [comment]
![image](https://user-images.githubusercontent.com/43878904/48219804-c9c7ab80-e38d-11e8-8726-2e4852f2c83d.png)
