### ISSUE TITLE
Erste Testversion bis nächsten freitag

### ISSUE THREAD

**Issue by Amaduesss** [sweIhm-ws2018-19/skillproject-fr-22#28]
Ich als Auftraggeber hätte gerne eine grobe Testversion bis zum 23.11

UAC

- Alexa sollte mir schon auf meine Anfrage ein Rezept vorschlagen können.

**Comment by juliakt** [comment]
![colorpicker pezepte](https://user-images.githubusercontent.com/43878732/48768905-a0c2e700-ecba-11e8-9444-cffab55970e5.png)

![colorpicker](https://user-images.githubusercontent.com/43878732/48768909-a1f41400-ecba-11e8-8bae-d487dc7eb95a.png)

![colorpicker handlers](https://user-images.githubusercontent.com/43878732/48768929-aae4e580-ecba-11e8-859d-c9ed759d2a0e.png)

und nochmal alles zusammen
![allclasses](https://user-images.githubusercontent.com/43878732/48768933-ad473f80-ecba-11e8-8a19-957143f8871a.png)

**Comment by juliakt** [comment]
Lukas hat gestern richtig viel gemacht, hier sind die passenden UML diagramme dazu. ich hab sie damit automatisch generieren lassen: [https://sourceforge.net/projects/essmodel/](https://sourceforge.net/projects/essmodel/)

**Comment by Zzerr0r** [comment]
UML Diagramme sind nichtmehr aktuell aufgrund von Umstrukturierungen

**Comment by toasthans** [comment]
![main java soupit](https://user-images.githubusercontent.com/43779031/49291257-f90f9b00-f4a9-11e8-9ff2-4fefc941fd55.jpg)
