### ISSUE TITLE
TODO Bekanntmachen mit Entwicklungs-Umgebung

### ISSUE THREAD

**Issue by Zzerr0r** [sweIhm-ws2018-19/skillproject-fr-22#31]
---------------------------------------------------------------------------------------------------------------
## Alexa skills kit SDK: 

- https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk-apache-client/src/com/amazon/ask/services/ApacheHttpApiClient.java

- https://github.com/alexa/alexa-skills-kit-sdk-for-java

  **configuration tutorial**
- https://alexa-skills-kit-sdk-for-java.readthedocs.io/en/latest/Setting-Up-The-ASK-SDK.html 
----------------------------------------------------------------------------------------------------------------
## Maven:

 **ECLIPSE**
- man braucht den Link nicht eclipse hat schon ein maven dingens

**INTELLIJ**
- https://www.jetbrains.com/help/idea/maven-support.html

schaut mal ob ihr das öffnen könnt sollte das gerüst für ein java projekt mit skillhandler sein

https://github.com/sweIhm-ws2018-19/skillproject-fr-22/files/2569566/test.zip

richtige version ^

**Comment by toasthans** [comment]
hab eine zip hinzugefügt schaut mal ob ihr das öffnen könnt

**Comment by Zzerr0r** [comment]
da is bei mir kein sourcecode drin, soll das so sein ? also nur xml dateien ?

**Comment by Zzerr0r** [comment]
ne ich kann die nicht öffnen

**Comment by toasthans** [comment]
ist halt jetzt ne gezipte jarr datei ich probiers nochmal

**Comment by Zzerr0r** [comment]
gibt es eine main.java.colorpicker.ColorPickerStreamHandler ?

**Comment by toasthans** [comment]
bei mir?

**Comment by Zzerr0r** [comment]
ja

**Comment by toasthans** [comment]
ne aber andere handler

**Comment by toasthans** [comment]
jetzt gehts ich hatte vorher ne jar datei... und die dann einfach gezipt

**Comment by Zzerr0r** [comment]
dass man das selber builden kann

**Comment by toasthans** [comment]
ne sollte in netbeans und eclipse schon gebundelt sein

**Comment by toasthans** [comment]
einfach importieren in ein leeres projekt
