### ISSUE TITLE
Zutaten verwenden die da sind

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#32]
Ich als Nutzer möchte von Alexa basierend auf Zutaten die ich im Kühlschrank habe Rezeptvorschläge bekommen, was dazu beitragen soll, dass insgesamt weniger Lebensmittel verschwendet werden indem sie schlecht werden.

UAC:

- Ich kann eine Auflistung von Zutaten nennen

- Alexa schlägt mir das Rezept mit den meisten Übereinstimmugen vor

- Wenn ich genau die selben Zutaten nenne bekomme ich aber nicht jedes mal das gleiche Rezept, sondern verschiedene

**Comment by Zzerr0r** [comment]
warum wurde ich grade erst assigned ? und wir nehmen jetzt einfach ein random rezept aber nur aus einer liste bei denen die übereinstimmung gleich ist, oder ?

**Comment by Zzerr0r** [comment]
ah jetzt versteh ichs, alles gut

**Comment by juliakt** [comment]
ja weil dus gemacht hast ^^ ja würd ich auch so sagen

**Comment by juliakt** [comment]
- [x] review done
