### ISSUE TITLE
Wichtige Fragen klären

### ISSUE THREAD

**Issue by Amaduesss** [sweIhm-ws2018-19/skillproject-fr-22#40]
Ich als Auftraggeber möchte folgende Fragen klären:

1. Schnittstelle zur Einkaufsliste auf Device generell möglich? 
2. Nachdem Zutaten (falls möglich) auf Einkaufsliste hinzugefügt worden sind:
 Ist es möglich das Wunschrezept zu speichern um anschließend (wenn die Zutaten alle eingekauft wurden) nach Signalwort im Rezept fortzufahren? (Die Anwendung sollte an der Stelle nicht von Vorne anfangen)
3. Mit den Profs klären ob beide Teams unsere eigene Datenbank hernehmen dürfen oder soll ein Team ggf. mit Schnittstelle arbeiten?

**Comment by EvelynSoupIt** [comment]
Zu 3. 
Ihr dürft mit Team Fr-12 gemeinsam eine Datenbank erstellen. Weitere Infos folgen demnächst.

**Comment by juliakt** [comment]
sehe ich das richtig dass diese Fragen geklärt sind? also was einkaufsliste angeht wollten wir das ja zurückstellen und das problem mit der datenbank haben wir ja mittlerweile auch gelöst
