### ISSUE TITLE
Wiki-Seite für den 1. Sprint

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#43]
Notieren Sie das Sprintziel und eine Zusammenfassung der wesentlichen User Stories auf der Wiki-Seite.

**Comment by juliakt** [comment]
schreibt das bitte mal jemand auf die wikiseite? halt einfach was wir besprochen haben, was wir schon gemacht und noch bis freitag vor haben


![whatsapp image 2018-11-26 at 05 58 54](https://user-images.githubusercontent.com/43878732/49085357-26faa280-f252-11e8-8521-6f24e4e6e7e6.jpeg)

**Comment by Zzerr0r** [comment]
wo auf die wiki seite ?

**Comment by Zzerr0r** [comment]
ok habs schon

**Comment by juliakt** [comment]
Unter dem Punkt Sprint 1, rechts an der seite
