### ISSUE TITLE
Alexa liest Zutaten grammatikalisch richtig vor

### ISSUE THREAD

**Issue by Zzerr0r** [sweIhm-ws2018-19/skillproject-fr-22#49]
Ich als User möchte, dass Alexa die Zutaten grammatikalisch richtig vorliest,

UAC:
- sie sagt nicht "eins Zwiebel" oder "0.5 Zwiebel" sondern "eine" oder "eine halbe" und "eine drittel" usw.
- sie benutzt das grammatikalisch richtige Geschlecht der Zutat oder der Einheit 
- zahlen sollen nicht .0 am ende haben

**Comment by juliakt** [comment]
- [x] reviewed
