### ISSUE TITLE
Übungsblatt 2

### ISSUE THREAD

**Issue by juliakt** [sweIhm-ws2018-19/skillproject-fr-22#5]

**Comment by juliakt** [comment]
es sind 9 aufgaben und wir sollen diesmal alles im team machen

**Comment by Zzerr0r** [comment]
und du fängst schonmal an ?

**Comment by juliakt** [comment]
weil das teilweise ein bisschen behindert ist mit der wiki seite hab ich die nützlichen tipps die ich bisher so gefunden hab mal zusammengefasst auf einer neuen seite. könnts gern ergänzen oder da nachlesen, falls ihr irgendein bild oder code ins wiki stellen wollt
